preload = $HOME/.config/hypr/wallaper/blade.jpg
wallpaper = , $HOME/.config/hypr/wallaper/blade.jpg

# preload = $HOME/Downloads/colorBerserk.png
# wallpaper = , $HOME/Downloads/colorBerserk.png

#wallpaper = monitor2,/path/to/next_image.png

# splash = true

#fully disable ipc
# ipc = off


